### ISSUE TITLE
Task :core-mvi:compileKotlin FAILED

### ISSUE THREAD

**Issue by LokNplay** [inotia00/VancedManager_v2#1]
Having this error while building release apk from source.
Please check [THIS](https://github.com/LokNplay/VancedManager_v2/runs/7314633562?check_suite_focus=true#step:6:320)

**Comment by inotia00** [comment]
> Having this error while building release apk from source. Please check [THIS](https://github.com/LokNplay/VancedManager_v2/runs/7314633562?check_suite_focus=true#step:6:320)
The github source of the Vanced Manager V2 is not yet completed.

Test the build with the Vanced Manager
https://github.com/inotia00/vancedManager

**Comment by LokNplay** [comment]
Okay
Thanks for your clarification.
I am closing this issue.
