### ISSUE TITLE
ads on home screen and in the player

### ISSUE THREAD

**Issue by skypeias** [inotia00/VancedManager_v2#11]
on the tablet version of the vanced app, ad banners on the home page and next to the video playing start showing up, even with the toggle switched on. 
![Screenshot_20220801-031737](https://user-images.githubusercontent.com/109490992/182093877-a90a6a67-06a5-4dda-b91b-fe021eff6bda.jpg)
![Screenshot_20220801-031700](https://user-images.githubusercontent.com/109490992/182093896-93fb4a4b-0e16-45eb-93ed-b842a8f09709.jpg)

**Comment by StrikerOnLine** [comment]
Dat vanced

**Comment by L-29kan** [comment]
> Dat vanced

**Comment by inotia00** [comment]
This is a KNOWN ISSUE (unsolvable issue)
