### ISSUE TITLE
Vanced Manager 2 is hamrfull app

### ISSUE THREAD

**Issue by rendykyh** [inotia00/VancedManager_v2#13]
![Screenshot_20220825-212858_Google Play Store](https://user-images.githubusercontent.com/38185582/186697632-52213da5-3564-4ecd-ace1-bd36020b00ba.png)

**Comment by LEx66** [comment]
false positive

**Comment by rendykyh** [comment]
i found solution, hide the vanced manager v2 with detach magisk...
