### ISSUE TITLE
Can't Install Over Original Vanced App/MicroG?

### ISSUE THREAD

**Issue by ShnikeJSB** [inotia00/VancedManager_v2#16]
I still have the latest of the "old" Vanced App and MicroG from the original Vanced Manager, but it will not update over them with the versions from this Manager V2. Are they just incompatible? I don't really want to uninstall the original version if this won't update and won't install side-by-side, either. Are you saying I'd have to completely uninstall the original versions and redo all my accounts and settings?

![Screenshot_20220829-202814_Vanced Manager v2](https://user-images.githubusercontent.com/112449901/187327631-e52b6cc2-3226-499a-b13a-f4ea03cc74bb.jpg)

![Screenshot_20220829-203223_Vanced Manager v2](https://user-images.githubusercontent.com/112449901/187328092-a7421d66-bdb7-43b1-a913-1e26643204cc.jpg)

**Comment by inotia00** [comment]
> I still have the latest of the "old" Vanced App and MicroG from the original Vanced Manager, but it will not update over them with the versions from this Manager V2. Are they just incompatible? I don't really want to uninstall the original version if this won't update and won't install side-by-side, either. Are you saying I'd have to completely uninstall the original versions and redo all my accounts and settings?
> 
> ![Screenshot_20220829-202814_Vanced Manager v2](https://user-images.githubusercontent.com/112449901/187327631-e52b6cc2-3226-499a-b13a-f4ea03cc74bb.jpg)
> 
> ![Screenshot_20220829-203223_Vanced Manager v2](https://user-images.githubusercontent.com/112449901/187328092-a7421d66-bdb7-43b1-a913-1e26643204cc.jpg)

signature is different
You need to uninstall the previously installed app and then install it.
