### ISSUE TITLE
Cant see what im writing i comments

### ISSUE THREAD

**Issue by JimZiii** [inotia00/VancedManager_v2#17]
I'm using the black version so it might just be on that version but i cant see what im typing, the background for the text box is white and the text is white.
I'm also wondering what the difference is between your two managers, the regular one and this one (v2).

Here's a screenshot of the comments.
![Screenshot_20220831-192056_YouTube.jpg](https://user-images.githubusercontent.com/7854537/187741243-9cc00960-4eac-409d-984d-8017288de4f5.jpg)

**Comment by inotia00** [comment]
This is a YouTube Issue
You probably have the same issue with Original YouTube

**Comment by JimZiii** [comment]
Nope, works fine on regular youtube, i took a screenshot for you from normal youtube.
I installed your app today, before than i was using the second last version of the original vanced (16.29.39) and it worked fine on that version as well.
So it doesnt seem to be a youtube issue

![Screenshot_20220831-224921_YouTube.jpg](https://user-images.githubusercontent.com/7854537/187780198-6483a966-3b49-4939-b465-2a3731f3d8d5.jpg)

**Comment by JimZiii** [comment]
I narrowed it down for you, up till version 17.28.34(RC) it's working fine but on version 17.32.38 the comment box turned white and i can't see the text. I also tried both black and regular dark version and they both have this issue

**Comment by JimZiii** [comment]
Oh ok, i thought you were still updating your app. Guess I'll just switch back to the original vanced app.
Thnx anyways
