### ISSUE TITLE
Running without microG: Crashes without it.

### ISSUE THREAD

**Issue by vegedb** [inotia00/VancedManager_v2#2]
I don't particularly use microg nor logging in on youtube.
Thus, having microg in the background is kinda redundant.

The last "official" youtube vanced works without microg installed. Could you bring this function back?

Edit: Revanced project works without any microG too.

**Comment by inotia00** [comment]
> I don't particularly use microg nor logging in on youtube. Thus, having microg in the background is kinda redundant.
> 
> The last "official" youtube vanced works without microg installed. Could you bring this function back?
> 
> Edit: Revanced project works without any microG too.

As of YouTube v17.26.xx, microG is mandatory.

YouTube ReVanced Also, for versions after v17.26.xx, if microG is not installed, it will not run.
Perhaps what you checked, it was YouTube ReVanced v17.25.35.

This is not a microG issue, the source on YouTube has changed.
