### ISSUE TITLE
Battery drain especially with Youtube Music

### ISSUE THREAD

**Issue by skypeias** [inotia00/VancedManager_v2#4]
If there's a way you can fix the battery drain in Youtube Music similar to how the original vanced app did that would be great because it is awful right now. my phone only lasts 4 hours with youtube music in the background

**Comment by RAVENz46** [comment]
I have same issue on my Android 11 device. And also micro G drain too much battery.

**Comment by inotia00** [comment]
This is a microg issue

Since development has already been stopped, there are no plans to fix
