### ISSUE TITLE
Youtube Vanced Crashes On opening 

### ISSUE THREAD

**Issue by RealJabran** [inotia00/VancedManager_v2#7]
I just downloaded the latest built "Unofficial Vanced Manager", installed MicroG, then Installed the Latest version of YouTube Vanced. Whenever I try to open the app, it crashes (closes) within 5 second's. 

I tried on both YouTube icon and vanced icon but still the same problem. 

I tried it on Android 10, and 11 both are giving the same problems.

**Comment by eisklwksjs** [comment]
Install microG first and open it

**Comment by RealJabran** [comment]
So I fixed the crash issue.

I disabled the official YouTube and re-installed the Vanced Manager and YouTube Vanced. 

After opening the YouTube Vanced, it again crashed automatically. 

Then, I forced stopped YouTube vanced and clear cache. It fixed the issue.
