### ISSUE TITLE
YouTube Music landscape mode not working on tablet

### ISSUE THREAD

**Issue by skypeias** [inotia00/VancedManager_v2#8]
I'm using Vanced Manager with the Vanced logo and when Im using YouTube music vanced on my galaxy tablet, the app doesn't turn into landscape mode

**Comment by edgardluz** [comment]
can confirm.App won't go into landscape mode on a fold 4. Using 3rd party app to force rotation works

**Comment by inotia00** [comment]
Enable tablet mode in Vanced settings
