### ISSUE TITLE
Request: Old Icons on Vanced?

### ISSUE THREAD

**Issue by arichorn** [inotia00/VancedManager_v2#9]
inotia00 not gonna lie I like that you ported Vanced to the newer versions! The original Vanced finally stopped working unfortunately but yours truly solved the problem so I think this version of YouTube Vanced should get a feature called OGIcons? I actually don’t know the name but I’ve seen posts about people seeing these on ReVanced
![0FE1DB8D-3454-4767-9831-1227750B9C4D](https://user-images.githubusercontent.com/78001398/181255004-7944a4bc-574b-41fd-9889-2fc1fa30a8a3.png)
But I actually wish these were back on YouTube, it’s been insane dealing with the outline ones for the past 2 years

**Comment by inotia00** [comment]
It is the part that depends on the back-end (server side)

There is no way to modify it on the front-end

**Comment by arichorn** [comment]
Yep should’ve expected that YouTube on android recently changed that. sorry devs!

**Comment by arichorn** [comment]
But hold on. on the YouTube for iOS someone made a tweak to disable YouTube’s New Server Side system on the icons but since it’s using iOS Code & YouTube Code for iOS then I don’t know if it’s possible for android but here’s this. The code might be hard to find but it is called "FakeVersion" in it. I’m just showing you the possibilities of YouTube Vanced missing and important feature. I was showing just an example so you don’t have to do it. https://github.com/PoomSmart/YouPiP/blob/main/Settings.x
